### PR TITLE
Update gsoc sumit

### PR DESCRIPTION
**Pull request by Sumit112192**
This PR updates the new section of my project. 
For now I have added a sharpened cover image
created a circle showing the memory optimization.
Adding boundary interaction info and numba toy codes

### CODE REVIEW

**Comment by Sumit112192** [comment]
@KasukabeDefenceForce can you force merge this?

**Comment by KasukabeDefenceForce** [comment]
> @KasukabeDefenceForce can you force merge this?

Yep doing it

**Comment by KasukabeDefenceForce** [comment]
> @KasukabeDefenceForce can you force merge this?

@Sumit112192  
image
The keys names are repetetive, can you fix that? delete the ones which are no longer needed.

**Comment by KasukabeDefenceForce** [comment]
https://github.com/tardis-sn/research_news/pull/54

@Sumit112192 I have fixed the merge conflicts and merged a new PR, we can close this one.

**Pull request closed without merging**
